[tool.poetry]
name = "easy_dwpose"
version = "1.0.2"
description = ""
authors = []

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
